services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: ""  # Set the root password
       MYSQL_DATABASE: fastapiblog
    ports:
      - "3306:3306"

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
        DATABASE_URL: "mysql+pymysql://root:yourpassword@db:3306/fastapiblog"


volumes:
  mysql_data:
