"""create_comments_table

Revision ID: 1e53f558e83c
Revises: a5e5aef6f09d
Create Date: 2024-12-15 21:47:08.235599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e53f558e83c'
down_revision: Union[str, None] = 'a5e5aef6f09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('comment', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'comment')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###
