"""Add onupdate to updated_at colum in Post Table

Revision ID: cf871bb5bffd
Revises: 49619daceff4
Create Date: 2024-12-13 02:23:30.524702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf871bb5bffd'
down_revision: Union[str, None] = '49619daceff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
