"""add_cascade_ondelete_to tables

Revision ID: e3440beeeae2
Revises: 1e53f558e83c
Create Date: 2024-12-18 09:27:13.810536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3440beeeae2'
down_revision: Union[str, None] = '1e53f558e83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
